In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(2022)

In [2]:
# Data Load
df = pd.read_csv("movies_metadata.csv")

C:\Users\sclab\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [3]:
# title, overview column만 사용
df = df[["title", "overview"]]

In [4]:
# 전체 중 1000개의 데이터만 사용
df = df.iloc[:1000]

In [5]:
df.shape

(1000, 2)

In [6]:
df

title  \
0                        Toy Story   
1                          Jumanji   
2                 Grumpier Old Men   
3                Waiting to Exhale   
4      Father of the Bride Part II   
..                             ...   
995           The Three Caballeros   
996         The Sword in the Stone   
997            So Dear to My Heart   
998  Robin Hood: Prince of Thieves   
999                   Mary Poppins   

                                              overview  
0    Led by Woody, Andy's toys live happily in his ...  
1    When siblings Judy and Peter discover an encha...  
2    A family wedding reignites the ancient feud be...  
3    Cheated on, mistreated and stepped on, the wom...  
4    Just when George Banks has recovered from his ...  
..                                                 ...  
995  For Donald's birthday he receives a box with t...  
996  Wart is a young boy who aspires to be a knight...  
997  The tale of Jeremiah Kincaid and his quest to ...  
998  When the dastardly Sheriff of Nottingham murde...  
999  The movie combines a diverting story, songs, c...  

[1000 rows x 2 columns]

In [7]:
# Data Cleaning
# overview의 결측치를 빈 str로 대체
df["overview"].isna().sum()

12

In [8]:
df["overview"] = df["overview"].fillna('')

In [9]:
# TF-IDF 계산
from sklearn.feature_extraction.text import TfidfVectorizer

In [10]:
# Sample Data
df["overview"].values[:2]

array(["Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.",
       "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures."],
      dtype=object)

In [11]:
transformer = TfidfVectorizer(stop_words='english')
tfidf_matrix = transformer.fit_transform(df['overview'].values[:2])

In [12]:
tfidf_matrix.toarray()

array([[0.        , 0.        , 0.14358239, 0.        , 0.43074717,
        0.14358239, 0.14358239, 0.        , 0.14358239, 0.43074717,
        0.14358239, 0.        , 0.14358239, 0.        , 0.        ,
        0.14358239, 0.        , 0.14358239, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.14358239, 0.14358239,
        0.        , 0.        , 0.        , 0.        , 0.14358239,
        0.14358239, 0.14358239, 0.14358239, 0.        , 0.14358239,
        0.        , 0.        , 0.        , 0.14358239, 0.        ,
        0.14358239, 0.14358239, 0.        , 0.        , 0.        ,
        0.10216005, 0.        , 0.14358239, 0.14358239, 0.        ,
        0.        , 0.14358239, 0.        , 0.        , 0.43074717,
        0.        , 0.        ],
       [0.15160873, 0.15160873, 0.        , 0.30321746, 0.        ,
        0.        , 0.        , 0.15160873, 0.        , 0.        ,
        0.        , 0.15160873, 0.        , 0.15160873, 0.15160873,
        0.     

In [13]:
# 추출된 단어 확인
transformer.get_feature_names()[:10]

['26',
 'adult',
 'afraid',
 'alan',
 'andy',
 'aside',
 'birthday',
 'board',
 'brings',
 'buzz']

In [14]:
pd.DataFrame(tfidf_matrix.toarray(), columns=transformer.get_feature_names()).T.head(10)

0         1
26        0.000000  0.151609
adult     0.000000  0.151609
afraid    0.143582  0.000000
alan      0.000000  0.303217
andy      0.430747  0.000000
aside     0.143582  0.000000
birthday  0.143582  0.000000
board     0.000000  0.151609
brings    0.143582  0.000000
buzz      0.430747  0.000000

In [15]:
# 학습
transformer = TfidfVectorizer(stop_words='english')

In [16]:
tfidf_matrix = transformer.fit_transform(df['overview'])

In [17]:
tfidf_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
transformer.get_feature_names()[-5:]

['zombies', 'zones', 'zookeeper', 'zorro', 'zulu']

In [19]:
# 영화별 유사도 계산 - 코사인 유사도
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
similarity = cosine_similarity(tfidf_matrix)

In [21]:
similarity

array([[1.        , 0.01570657, 0.        , ..., 0.        , 0.        ,
        0.01234882],
       [0.01570657, 1.        , 0.05047128, ..., 0.        , 0.01578968,
        0.02378018],
       [0.        , 0.05047128, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.01578968, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.01234882, 0.02378018, 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [22]:
# 인덱스 998번과 유사한 영화 추천
idx = 998
print(df.loc[idx, 'title'])

Robin Hood: Prince of Thieves


In [23]:
similarity_one_idx = similarity[idx]

In [24]:
# argsort로 유사도가 큰 인덱스를 정렬
# argsort는 작은 것부터 정렬을 하는데, -1을 줘서 유사도가 큰 것부터 정렬
order_idx = similarity_one_idx.argsort()[::-1]

In [25]:
order_idx[:100]

array([998, 515, 913, 215, 779, 598,  43, 150, 675,   3, 392, 148, 181,
        25,  99, 231, 241, 548, 725, 363, 331, 447, 988, 207, 270, 804,
       256, 517, 940, 807, 401, 319, 245, 660, 977, 400,  18, 648,  11,
       695, 459, 621, 402, 503, 903, 135, 971, 594, 790, 975, 185, 978,
       513, 823, 883, 408, 853, 628, 944, 668, 663,  64, 446, 147, 953,
       718, 240, 264, 670, 642, 484, 742, 461, 857, 178, 797, 295, 671,
       763, 412, 470, 564, 243,  54, 268, 829, 841, 547, 890,   8, 597,
        13, 623, 778, 581, 768, 316, 867, 777, 133], dtype=int64)

In [26]:
# 가장 큰 5개만 출력
top5 = order_idx[:6]
top5

array([998, 515, 913, 215, 779, 598], dtype=int64)

In [27]:
df.loc[top5, 'title']

998      Robin Hood: Prince of Thieves
515          Robin Hood: Men in Tights
913       The Adventures of Robin Hood
215                   Boys on the Side
779                          Lone Star
598    Candyman: Farewell to the Flesh
Name: title, dtype: object