In [1]:
import tensorflow as tf
from tensorflow.keras import Model, layers
import numpy as np

In [2]:
# Model

In [6]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        
        self.mlp1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.mlp2 = layers.Dense(hidden_2, activation="relu")
        self.mlp3 = layers.Dense(num_classes)
        
    def call(self, x):
        out = self.mlp1(x)
        out = self.mlp2(x)
        out = self.mlp3(x)
        out = tf.nn.softmax(out)
        return out

In [7]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

In [8]:
model = NeuralNet(hidden_1, hidden_2, num_classes)

In [9]:
data = tf.random.normal(shape=(1,28*28), mean=0., stddev=1.)
print('data:', data.shape)

data: (1, 784)


In [11]:
pred = model(data)
print('pred:', pred)

pred: tf.Tensor(
[[0.00630974 0.00543033 0.01398942 0.0413799  0.02784632 0.17376176
  0.12105147 0.0272448  0.56184614 0.02114013]], shape=(1, 10), dtype=float32)


In [12]:
y_hat = tf.argmax(pred, 1)
print('y_hat:', y_hat)

y_hat: tf.Tensor([8], shape=(1,), dtype=int64)


In [13]:
# layers.Dense

In [14]:
x = tf.random.normal(shape=(3,28,28), mean=0., stddev=1.)

In [15]:
fc_layer = layers.Dense(100)
x_after_fc = fc_layer(tf.reshape(x,(-1,28*28)))
print('x_after_fc:', x_after_fc.shape)
print(x_after_fc[0][:10])

x_after_fc: (3, 100)
tf.Tensor(
[ 1.4906249  -0.91943187  0.10301065  1.7937059   0.57692206  2.931439
 -0.2809884   0.39027154  0.8239373  -1.3761275 ], shape=(10,), dtype=float32)


In [16]:
fc_layer = layers.Dense(100, activation='relu')
x_after_fc = fc_layer(tf.reshape(x, (3,28*28)))
x_after_fc.shape

TensorShape([3, 100])

In [17]:
x_after_fc[0][:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([3.018399  , 0.98217297, 0.7342616 , 0.        , 2.625508  ,
       0.        , 0.        , 2.3521438 , 0.9003216 , 0.        ],
      dtype=float32)>

In [18]:
# Softmax

In [19]:
x = tf.random.normal(shape=(1,10), mean=0., stddev=1.)
x

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-1.2650627 , -0.19016781,  0.51135355, -0.68425393, -0.2576717 ,
         1.6128616 ,  0.50090605, -0.89512753,  0.45894068,  0.32010835]],
      dtype=float32)>

In [20]:
pred = tf.nn.softmax(x)
print('pred:', pred)
print('sum of pred:', tf.reduce_sum(pred))

pred: tf.Tensor(
[[0.02003063 0.05868345 0.11835387 0.03580443 0.05485284 0.35609132
  0.1171238  0.02899716 0.11231039 0.09775203]], shape=(1, 10), dtype=float32)
sum of pred: tf.Tensor(0.9999999, shape=(), dtype=float32)


In [21]:
# tf.keras.Sequential

In [28]:
class NeuralNet(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = layers.Dense(hidden_1, activation=tf.nn.relu)
        self.fc2 = layers.Dense(hidden_2, activation=tf.nn.relu)
        self.out = layers.Dense(num_classes)

    def call(self, x):
        out = self.fc1(x)
        out = self.fc2(x)
        out = self.out(x)
        out = tf.nn.softmax(x)
        return out

In [29]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet(hidden_1, hidden_2, num_classes)

In [30]:
class NeuralNet2(Model):
    def __init__(self, hidden_1, hidden_2, num_classes):
        super(NeuralNet2, self).__init__()
        
        self.sequential = tf.keras.Sequential([
            layers.Dense(hidden_1, activation=tf.nn.relu),
            layers.Dense(hidden_2, activation="relu"),
            layers.Dense(num_classes, activation=tf.nn.softmax)
        ])
        
    def call(self, x):
        out = self.sequential(x)
        return out

In [31]:
hidden_1 = 128
hidden_2 = 256
num_classes = 10

model = NeuralNet2(hidden_1, hidden_2, num_classes)

In [32]:
# Sequential + add
model = tf.keras.Sequential()

In [33]:
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [37]:
# Compile

In [38]:
model.compile(loss='categorical_crossentropy', # labels가 one-hot일 경우 사용
              optimizer='sgd',
              metrics=['accuracy'])

In [39]:
model.compile(loss='sparse_categorical_crossentropy', # labels가 integer일 경우 사용
              optimizer='adam',
              metrics=['accuracy'])

In [40]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3), # learning rate 설정
              metrics=['accuracy'])